#include <QtWidgets>
#include <windowsx.h>
#include "dwmapi.h"
#include <QEvent>
#include <QMouseEvent>
#include <QMap>
#include <QFont>
#include <QPalette>
#include <QPropertyAnimation>
#include <QtGlobal>
#include <QAction>
#include <QWidgetAction>
#include <QLayout>
#include <QStackedWidget>
#include <QTimer>
#include "Foundation/Effect/WindowCompositionAttribute.h"
#include "Foundation/Effect/CustomShadowEffect.h"
#include "Foundation/Control/ImageWidget.h"
#include "Foundation/Control/Label.h"
#include "Foundation/Control/Slider.h"
#include "Foundation/Control/Menu.h"
#include "Foundation/Control/SystemTray.h"
#include "Foundation/View/AboutView.h"
#include "Foundation/View/SettingView.h"
#include "Foundation/View/InformationView.h"

